### ISSUE TITLE
Failed to activate the atom-csso package

### ISSUE THREAD

**Issue by mrpunkin** [1000ch/atom-csso#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.198.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-csso](https://github.com/1000ch/atom-csso) package, v0.2.0

### Stack Trace

Failed to activate the atom-csso package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/Bryan/.atom/packages/atom-csso/lib/csso.coffee:13:25)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:242:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:223:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:215:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:418:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:413:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:394:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "fizzy"
    ],
    "projectHome": "/Users/Bryan/Sites"
  }
}
```

### Installed Packages

```coffee
# User
atom-csso, v0.2.0
close-tags, v0.2.0
emmet, v2.3.9
file-icons, v1.5.5
fizzy, v0.15.0
language-apache, v1.3.0
language-csharp, v0.5.0
language-liquid, v0.2.0

# Dev
No dev packages
```

**Comment by 1000ch** [comment]
@mrpunkin It seems to be old package (`atom-csso, v0.2.0`).
Would you try with `v0.3.1`?

**Comment by mrpunkin** [comment]
Yeah that version seems to work fine.

**Comment by 1000ch** [comment]
Thank you for reporting :)
