### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGrammar' of undefined

### ISSUE THREAD

**Issue by andy12530** [1000ch/atom-csso#2]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.205.0
**System**: Mac OS X 10.10.3
**Thrown From**: [csso](https://github.com/1000ch/atom-csso) package, v1.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getGrammar' of undefined

```
At /Users/zhangbingbing/.atom/packages/csso/lib/csso.coffee:54

TypeError: Cannot read property 'getGrammar' of undefined
    at Object.module.exports.restructure (/Users/zhangbingbing/.atom/packages/csso/lib/csso.coffee:72:27)
    at atom-workspace.<anonymous> (/Users/zhangbingbing/.atom/packages/csso/lib/csso.coffee:20:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
    at jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
```

### Commands

```
     -0:15.1.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".*"
    ]
  }
}
```

### Installed Packages

```coffee
# User
csso, v1.0.0
jsformat, v0.9.0
jshint, v1.3.7
minimap, v4.9.2

# Dev
No dev packages
```

**Comment by 1000ch** [comment]
@andy12530 Thank you for reporting and sorry for plugin error.
Would you tell me if you still get errors after updating your Atom and plugins?
