### ISSUE TITLE
Uncaught Error: Please check the validity of the CSS block starting from the line #26

### ISSUE THREAD

**Issue by corysimmons** [1000ch/atom-csso#3]
[Enter steps to reproduce below:]

1. Add sanitize.css
2. Try to minify

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [csso](https://github.com/1000ch/atom-csso) package, v1.2.0

### Stack Trace

Uncaught Error: Please check the validity of the CSS block starting from the line #26

```
At /Users/cory/.atom/packages/csso/node_modules/csso/lib/parser/index.js:115

Error: Please check the validity of the CSS block starting from the line #26
    at throwError (/Users/cory/.atom/packages/csso/node_modules/csso/lib/parser/index.js:115:11)
    at getBlock (/Users/cory/.atom/packages/csso/node_modules/csso/lib/parser/index.js:523:14)
    at getRuleset (/Users/cory/.atom/packages/csso/node_modules/csso/lib/parser/index.js:1595:18)
    at getStylesheet (/Users/cory/.atom/packages/csso/node_modules/csso/lib/parser/index.js:1797:52)
    at Object.CSSPRules.stylesheet (/Users/cory/.atom/packages/csso/node_modules/csso/lib/parser/index.js:80:65)
    at parse (/Users/cory/.atom/packages/csso/node_modules/csso/lib/parser/index.js:2108:30)
    at Object.minify (/Users/cory/.atom/packages/csso/node_modules/csso/lib/index.js:33:15)
    at minify (/Users/cory/.atom/packages/csso/index.js:25:20)
    at atom-workspace.<anonymous> (/Users/cory/.atom/packages/csso/index.js:35:60)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  6x -1:34.9.0 core:move-right (atom-text-editor.editor.is-focused)
  5x -1:32.8.0 core:move-down (atom-text-editor.editor.is-focused)
 18x -1:30.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:28.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:28.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:25.1.0 application:new-file (atom-text-editor.editor.is-focused)
     -1:21.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:16.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:14.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:14.5.0 csso:execute (atom-text-editor.editor)
     -0:11.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:10.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:10.2.0 set-syntax:CSS (atom-text-editor.editor)
     -0:09.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:07.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.2.0 csso:minify (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "linter-scss-lint",
      "linter-flake8",
      "linter-stylelint"
    ],
    "openEmptyEditorOnStart": false
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.2.1
advanced-open-file, v0.14.1
aligner, v0.18.1
atom-beautify, v0.28.21
auto-detect-indentation, v0.4.2
autocomplete-python, v1.6.1
csso, v1.2.0
editorconfig, v1.2.4
emmet, v2.4.1
git-hide, v0.1.2
linter, v1.11.3
linter-eslint, v6.0.0
linter-js-standard, v3.2.1
linter-jshint, v1.3.0
linter-phpcs, v1.3.0
markdown-preview-plus, v2.2.2
open-in-browser, v0.4.6
set-syntax, v0.3.0
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by 1000ch** [comment]
You know, `sanitize.css` includes cssnext syntax (not supported in CSSO's css parser).
CSSO accepts pure CSS syntax only now :(

**Comment by corysimmons** [comment]
Yeah I see that now. My bad. =)
