### ISSUE TITLE
Error on finding csso module

### ISSUE THREAD

**Issue by hoishing** [1000ch/atom-csso#7]
Hi, I got the following error when I apply csso. Seems that it can't locate the csso module. Any idea on how can I fix this?

```
Error: Command failed: 
/Users/hoishing/.atom/packages/csso/node_modules/.bin/csso 
internal/modules/cjs/loader.js:613 throw err; ^

Error: Cannot find module 'csso' Require stack:

/Users/hoishing/.atom/packages/csso/node_modules/csso-cli/index.js
/Users/hoishing/.atom/packages/csso/node_modules/csso-cli/bin/csso 
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15) 
at Function.Module._load (internal/modules/cjs/loader.js:526:27) 
at Module.require (internal/modules/cjs/loader.js:666:19) 
at require (internal/modules/cjs/helpers.js:16:16) 
at Object. (/Users/hoishing/.atom/packages/csso/node_modules/csso-cli/index.js:4:12) 
at Module._compile (internal/modules/cjs/loader.js:759:30) 
at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10) 
at Module.load (internal/modules/cjs/loader.js:628:32) 
at Function.Module._load (internal/modules/cjs/loader.js:555:12) 
at Module.require (internal/modules/cjs/loader.js:666:19)
```

**Comment by 1000ch** [comment]
Did you try re-install `atom-csso`?

**Comment by hoishing** [comment]
re-installing `atom-csso` couldn't solve the problem.

btw, when I go the package folder and run `npm list`

it has the following error:

`npm ERR! missing: csso@^3.2.0, required by csso-cli@1.1.0`

so I tried to update the dependencies by running `npm install`

afterwards everything is ok again.

However, I don't know why `csso@^3.2.0` is not installed during the installation of `atom-csso`, as its required by `csso-cli`
